"{\
  'general':\
  {\
    'name':'Chime',\   
    'instance':3,\
    'interval':2000\
  },\
  'components':[\
    {\
      'name':'DecagonGS3',\
      'params':[11, 1]\
    },\
    {\
      'name':'TSL2591',\
      'params':'default'\
    },\
    {\
      'name':'SD',\
      'params':[true,1000,10,'chimes',true]\
    },\
    {\
      'name':'InterruptManager',\
      'params':[0]\
    },\
    {\
      'name':'SleepManager',\
      'params':[true,false,1]\
    },\
    {\
      'name':'DS3231',\
      'params':[10, false, true]\
    },\
    {\
      'name':'SHT31D',\
      'params':'default'\
    }\
  ]\
}"
