"{\
  'general':\
  {\
    'name':'WeatherChimes',\   
    'instance':1,\
    'interval':2000\
  },\
  'components':[\
    {\
      'name':'TSL2591',\
      'params':'default'\
    },\
    {\
      'name':'SD',\
      'params':[true,1000,10,'chimes',true]\
    },\
    {\
      'name':'DS3231',\
      'params':[10, false, true]\
    },\
    {\
      'name':'SHT31D',\
      'params':'default'\
    }\
  ]\
}"
