"{\
  'general':\
  {\
    'name':'Rij',\
    'instance':4,\
    'interval':2000\
  },\
  'components':[\
    {\
      'name':'TSL2591',\
      'params':'default'\
    },\
    {\
      'name':'SD',\
      'params':[true,1000,10,'test',true]\
    },\
    {\
      'name':'SHT31D',\
      'params':'default'\
    },\
    {\
      'name':'Multiplexer',\
      'params':'default'\
     },\
    {\
      'name':'WiFi',\
      'params':['NETGEAR33','tinybolt321']\
    }\
  ]\
}"
